version: '3'

services:
  discord_geminiai:
    build: .
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SETTING_CHANNEL_ID=${SETTING_CHANNEL_ID}
      - CHAT_CHANNEL_ID=${CHAT_CHANNEL_ID}
      - RESET_CHAT_CHANNEL_ID=${RESET_CHAT_CHANNEL_ID}
      - HELP_CMD_CHANNEL_ID=${HELP_CMD_CHANNEL_ID}